List<String> districtsList = [
  'Faraskhana',
  'Koregaon',
  'Kothrud',
  'Lashkar',
  'Sahakar Nagar',
  'Samartha',
  'Shivaji Nagar',
  'Vishrambag',
  'Yerwada',
  'Chaturshrungi',
  'Khadaki',
  'Vimantal',
  'Hadapsar',
  'Wanwadi',
  'Lashkar',
  'Swargate',
  'Bundgarden',
  'Warje',
  'Deccan',
  'Dattawadi',
  'Bharati Vidyapeeth',
];

List<String> typeOfAccident = [
  'Mild',
  'Fatal',
  'Grievance',
];

List<String> reasonOfAccident = [
  'Collision from front',
  'Collision from back',
  'Bumper to bumper collision',
  'Right side collision',
  'Head on collision',
  'Left side collision',
  'Collision due to opposite direction drive',
  'Collided on wall on right side of canal',
  'Collided to iron platform',
  'Collision by PMT bus while waiting on bus stop',
  'Collision by car while standing in the chowk',
  'Collision by truck while standing in the chowk',
  'Collision by unknown vehicle',
  'Collision during road crossing',
  'Others',
];
