String apiKey = "<API KEY HERE>";
List<String> districtsList = [

  "FARASKHANA",
  "KOREGAON",
  "KOTHRUD",
  "LASHKAR",
  "SAHAKAR_NAGAR",
  "SAMARTHA",
  "SHIVAJI_NAGAR",
  "VISHRAMBAG",
  "YERWADA",
  "CHATURSHRUNGI",
  "KHADAKI",
  "KHADAK",
  "KONDHAWA",
  "DHANKAWADI",
  "VIMANTAL",
  "HADAPSAR",
  "WANWADI",
  "SWARGATE",
  "BUNDGARDEN",
  "WARJE",
  "DECCAN",
  "DATTAWADI",
  "BHARATI_VIDYAPEETH",
  "UNKNOWN"
];

List<String> typeOfAccident = [
  'MILD',
  'FATAL',
  'GRIEVANCE',
];

List<String> reasonOfAccident = [

  "FROM_FRONT",
  "FROM_BACK",
  "BUMPER_TO_BUMPER",
  "RIGHT_SIDE",
  "HEAD_ON",
  "LEFT_SIDE",
  "DUE_TO_OPPOSITE_DIRECTION_DRIVE",
  "COLLIDED_ON_WALL_ON_RIGHT_SIDE_OF_CANAL",
  "COLLIDED_TO_IRON_PLATFORM",
  "BY_PMT_BUS_WHILE_WAITING_ON_BUS_STOP",
  "BY_CAR_WHILE_STANDING_IN_THE_CHOWK",
  "BY_TRUCK_WHILE_STANDING_IN_THE_CHOWK",
  "UNKNOWN_VEHICLE",
  "DURING_ROAD_CROSSING",
  "OTHERS",
];

List<String> typeOfNOC = [
  "ROAD_DIGGING", "YEARLY_FESTIVAL","COMBINED"
];


List<String> typeOfPotHole = ["Pot holes", "Water logging"];
